"""
ShipSage Exporter - Creates ZIP archives of generated DevOps configurations
"""
import io
import zipfile
from datetime import datetime


def create_export_zip(analysis_data: dict, configs: dict) -> io.BytesIO:
    """
    Create a ZIP file containing all generated configurations.
    
    Args:
        analysis_data: Repository analysis metadata
        configs: Dictionary of config_name -> content
    
    Returns:
        BytesIO object containing the ZIP file
    """
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        repo_name = analysis_data.get('repo', 'project').replace('/', '-')
        base_dir = f"shipsage-{repo_name}"
        
        # Add README with setup instructions
        readme_content = generate_readme(analysis_data)
        zip_file.writestr(f"{base_dir}/README.md", readme_content)
        
        # Add Dockerfile
        if configs.get('dockerfile'):
            zip_file.writestr(f"{base_dir}/Dockerfile", configs['dockerfile'])
        
        # Add docker-compose.yml
        if configs.get('compose'):
            zip_file.writestr(f"{base_dir}/docker-compose.yml", configs['compose'])
        
        # Add Kubernetes manifests
        if configs.get('kubernetes'):
            zip_file.writestr(f"{base_dir}/k8s/manifests.yaml", configs['kubernetes'])
        
        # Add GitHub Actions workflow
        if configs.get('cicd'):
            zip_file.writestr(f"{base_dir}/.github/workflows/main.yml", configs['cicd'])
        
        # Add Terraform
        if configs.get('aws_terraform'):
            zip_file.writestr(f"{base_dir}/terraform/main.tf", configs['aws_terraform'])
        
        # Add monitoring stack
        if configs.get('monitoring'):
            zip_file.writestr(f"{base_dir}/monitoring/docker-compose.monitoring.yml", configs['monitoring'])
        
        # Add env and nginx configs
        if configs.get('env_config'):
            content = configs['env_config']
            # Split env and nginx if both are present
            if '# === nginx.conf' in content or '# ══════════════════════════════════════' in content:
                parts = content.split('# ══════════════════════════════════════')
                if len(parts) >= 2:
                    zip_file.writestr(f"{base_dir}/config/.env.template", parts[0].strip())
                    nginx_content = parts[1].strip()
                    if len(parts) >= 3:
                        nginx_content = parts[1].strip()
                        zip_file.writestr(f"{base_dir}/config/nginx.conf", nginx_content)
                        # Add Airflow DAG if present
                        if len(parts) >= 4:
                            airflow_content = parts[3].strip()
                            zip_file.writestr(f"{base_dir}/airflow/dags/data_pipeline.py", airflow_content)
                    else:
                        zip_file.writestr(f"{base_dir}/config/nginx.conf", nginx_content)
                else:
                    zip_file.writestr(f"{base_dir}/config/.env.template", content)
            else:
                zip_file.writestr(f"{base_dir}/config/.env.template", content)
        
        # Add analysis summary
        summary_content = generate_summary_file(analysis_data)
        zip_file.writestr(f"{base_dir}/ANALYSIS.md", summary_content)
    
    zip_buffer.seek(0)
    return zip_buffer


def generate_readme(analysis_data: dict) -> str:
    """Generate a README file for the exported configs."""
    repo = analysis_data.get('repo', 'your-project')
    stack = ', '.join(analysis_data.get('stack', ['Unknown']))
    project_type = analysis_data.get('project_type', 'Application')
    
    return f"""# {repo} - DevOps Configuration

**Generated by ShipSage** on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Project Overview

- **Type**: {project_type}
- **Tech Stack**: {stack}
- **Repository**: https://github.com/{repo}

## What's Included

This package contains production-ready DevOps configurations:

### 🐳 Container Setup
- `Dockerfile` - Multi-stage optimized container build
- `docker-compose.yml` - Local development orchestration

### ☸️ Kubernetes
- `k8s/manifests.yaml` - Deployment, Service, Ingress, HPA, ConfigMap, Secrets

### 🔄 CI/CD
- `.github/workflows/main.yml` - Automated build, test, and deploy pipeline

### ☁️ Infrastructure
- `terraform/main.tf` - AWS infrastructure (VPC, EKS, ECR, RDS/DocumentDB, S3)

### 📊 Monitoring
- `monitoring/docker-compose.monitoring.yml` - ELK Stack + Prometheus + Grafana

### ⚙️ Configuration
- `config/.env.template` - Environment variables template
- `config/nginx.conf` - Reverse proxy configuration

## Quick Start

### 1. Local Development

```bash
# Copy environment template
cp config/.env.template .env

# Edit .env with your values
nano .env

# Start with Docker Compose
docker-compose up -d
```

### 2. Build Docker Image

```bash
docker build -t {repo.split('/')[-1]}:latest .
docker run -p 8000:8000 --env-file .env {repo.split('/')[-1]}:latest
```

### 3. Deploy to Kubernetes

```bash
# Update image registry in k8s/manifests.yaml
# Update secrets and config values

kubectl apply -f k8s/manifests.yaml
kubectl get pods -n app-production
```

### 4. Provision AWS Infrastructure

```bash
cd terraform
terraform init
terraform plan
terraform apply
```

### 5. Set Up CI/CD

1. Add GitHub Secrets:
   - `AWS_ROLE_ARN` - IAM role for GitHub Actions
   - `ACM_CERT_ARN` - SSL certificate ARN (for ingress)

2. Push to main branch to trigger deployment

### 6. Set Up Monitoring

```bash
cd monitoring
docker-compose -f docker-compose.monitoring.yml up -d

# Access dashboards:
# Kibana: http://localhost:5601
# Grafana: http://localhost:3001 (admin/admin)
# Prometheus: http://localhost:9090
```

## Important Notes

⚠️ **Before Production Deployment:**

1. **Review all configurations** - These are starter templates
2. **Update secrets** - Change all placeholder passwords and keys
3. **Configure domains** - Replace `app.example.com` with your domain
4. **Set resource limits** - Adjust CPU/memory based on your needs
5. **Enable backups** - Configure database backup strategies
6. **Security scan** - Run vulnerability scans on Docker images
7. **Load testing** - Test under expected traffic loads

## Next Steps

1. Read `ANALYSIS.md` for detailed repository insights
2. Customize configs for your specific needs
3. Set up monitoring and alerting
4. Configure auto-scaling policies
5. Implement backup and disaster recovery
6. Set up staging environment
7. Document runbooks for common operations

## Support

Generated configurations are starting points. Always review and test before production use.

For issues with ShipSage: https://github.com/AbhishekKharat04/repo-sage

---

*Generated by [ShipSage](https://github.com/AbhishekKharat04/repo-sage) - AI DevOps Pipeline Generator*
"""


def generate_summary_file(analysis_data: dict) -> str:
    """Generate an analysis summary file."""
    repo = analysis_data.get('repo', 'Unknown')
    branch = analysis_data.get('branch', 'main')
    total_files = analysis_data.get('total_files', 0)
    analyzed_files = analysis_data.get('analyzed_files', 0)
    stack = analysis_data.get('stack', [])
    project_type = analysis_data.get('project_type', 'Unknown')
    ai_powered = analysis_data.get('ai_powered', False)
    readiness = analysis_data.get('readiness', {})
    
    content = f"""# Repository Analysis Summary

**Repository**: {repo}  
**Branch**: {branch}  
**Analysis Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**AI Engine**: {'IBM watsonx Granite' if ai_powered else 'Rule-based Analysis'}

## Statistics

- **Total Files**: {total_files}
- **Files Analyzed**: {analyzed_files}
- **Project Type**: {project_type}

## Technology Stack

{chr(10).join(f'- {s}' for s in stack)}

## DevOps Readiness Score

**Score**: {readiness.get('score', 0)}/100  
**Status**: {readiness.get('status', 'Unknown')}

### Summary
{readiness.get('summary', 'No summary available')}

### Production Signals

"""
    
    signals = readiness.get('signals', {})
    for key, value in signals.items():
        status = '✅' if value else '❌'
        labels = {
            'tests': 'Automated Tests',
            'ci': 'CI/CD Pipeline',
            'docker': 'Container Setup',
            'env_template': 'Environment Template',
            'docs': 'Documentation',
            'health': 'Health Checks',
            'infra': 'Infrastructure as Code'
        }
        content += f"{status} **{labels.get(key, key.title())}**: {'Present' if value else 'Missing'}\n"
    
    blockers = readiness.get('blockers', [])
    if blockers:
        content += "\n### ⚠️ Deployment Blockers\n\n"
        for blocker in blockers:
            content += f"- {blocker}\n"
    
    next_actions = readiness.get('next_actions', [])
    if next_actions:
        content += "\n### 📋 Recommended Next Steps\n\n"
        for i, action in enumerate(next_actions, 1):
            content += f"{i}. {action}\n"
    
    content += f"\n---\n\n*Analysis powered by ShipSage*\n"
    
    return content

# Made with Bob
