"""
ShipSage Generators — produces production-ready DevOps configs from detected tech stack.
"""


def gen_dockerfile(stack: list, project_type: str, files: list) -> str:
    """Generate an optimized multi-stage Dockerfile."""
    lang = _detect_primary_lang(stack)
    templates = {
        "python": _dockerfile_python(files),
        "node": _dockerfile_node(files),
        "go": _dockerfile_go(files),
        "java": _dockerfile_java(),
        "rust": _dockerfile_rust(),
    }
    df = templates.get(lang, _dockerfile_python(files))
    return f"# === Dockerfile ===\n# Generated by ShipSage — AI DevOps Pipeline Generator\n# Optimized multi-stage build for {lang}\n\n{df}"


def gen_compose(stack: list, files: list) -> str:
    """Generate docker-compose.yml with detected services."""
    lang = _detect_primary_lang(stack)
    port = {"python": "8000", "node": "3000", "go": "8080", "java": "8080", "rust": "8080"}.get(lang, "8000")
    services = f"""# === docker-compose.yml ===
# Generated by ShipSage

version: '3.9'

services:
  app:
    build: .
    container_name: app
    ports:
      - "{port}:{port}"
    env_file: .env
    restart: unless-stopped
    depends_on:"""

    db_services = ""
    has_pg = any(k in stack for k in ["PostgreSQL", "Django", "SQLAlchemy"])
    has_mongo = "MongoDB" in stack or any("mongo" in f.lower() for f in files)
    has_redis = "Redis" in stack or any("redis" in f.lower() for f in files)

    deps = []
    if has_pg:
        deps.append("postgres")
        db_services += """
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: \${DB_USER:-app}
      POSTGRES_PASSWORD: \${DB_PASS:-secret}
      POSTGRES_DB: \${DB_NAME:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      retries: 5"""

    if has_mongo:
        deps.append("mongo")
        db_services += """
  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: \${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: \${MONGO_PASS:-secret}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db"""

    if has_redis:
        deps.append("redis")
        db_services += """
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data"""

    if deps:
        services += "\n" + "\n".join(f"      {d}:\n        condition: service_started" for d in deps)
    else:
        services += " []"

    services += "\n    networks:\n      - app-network"
    db_services_with_net = ""
    for line in db_services.split("\n"):
        db_services_with_net += line + "\n"

    volumes = "\nvolumes:"
    if has_pg: volumes += "\n  pg_data:"
    if has_mongo: volumes += "\n  mongo_data:"
    if has_redis: volumes += "\n  redis_data:"
    if not any([has_pg, has_mongo, has_redis]): volumes += " {}"

    return f"""{services}
{db_services}

networks:
  app-network:
    driver: bridge
{volumes}"""


def gen_kubernetes(stack: list, project_type: str) -> str:
    """Generate Kubernetes manifests: Deployment, Service, Ingress, HPA, ConfigMap."""
    lang = _detect_primary_lang(stack)
    port = {"python": 8000, "node": 3000, "go": 8080, "java": 8080}.get(lang, 8000)

    return f"""# === Kubernetes Manifests ===
# Generated by ShipSage

# --- Namespace ---
apiVersion: v1
kind: Namespace
metadata:
  name: app-production
---
# --- ConfigMap ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-production
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "{port}"
---
# --- Secret (base64 encoded) ---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-production
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0  # "secret" — CHANGE IN PRODUCTION
  API_KEY: Y2hhbmdlbWU=   # "changeme" — CHANGE IN PRODUCTION
---
# --- Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-production
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ${{ECR_REGISTRY}}/app:latest
          ports:
            - containerPort: {port}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: {port}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {port}
            initialDelaySeconds: 5
            periodSeconds: 10
---
# --- Service ---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-production
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 80
      targetPort: {port}
      protocol: TCP
---
# --- Ingress (AWS ALB) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-production
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: ${{ACM_CERT_ARN}}
    alb.ingress.kubernetes.io/listen-ports: '[{{"HTTPS":443}}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
---
# --- HorizontalPodAutoscaler ---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: app-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70"""


def gen_cicd(stack: list, files: list) -> str:
    """Generate GitHub Actions CI/CD pipeline with AWS ECR + EKS deploy."""
    lang = _detect_primary_lang(stack)
    has_tests = any("test" in f.lower() for f in files)
    test_cmd = {"python": "pytest", "node": "npm test", "go": "go test ./...", "java": "mvn test"}.get(lang, "echo 'No tests'")
    build_cmd = {"python": "pip install -r requirements.txt", "node": "npm ci", "go": "go build ./...", "java": "mvn package"}.get(lang, "echo 'Build'")

    return f"""# === GitHub Actions CI/CD Pipeline ===
# Generated by ShipSage — Build → Test → Push to ECR → Deploy to EKS

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: app
  EKS_CLUSTER: app-cluster
  IMAGE_TAG: ${{{{ github.sha }}}}

jobs:
  # ── Stage 1: Lint & Test ──
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: {"actions/setup-python@v5\\n        with:\\n          python-version: '3.12'" if lang == "python" else "actions/setup-node@v4\\n        with:\\n          node-version: '20'" if lang == "node" else "actions/setup-go@v5\\n        with:\\n          go-version: '1.22'" if lang == "go" else "actions/setup-java@v4\\n        with:\\n          java-version: '21'"}

      - name: Install dependencies
        run: {build_cmd}

      - name: Run tests
        run: {test_cmd if has_tests else "echo 'No test suite detected — add tests!'"}

  # ── Stage 2: Build & Push Docker Image ──
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ secrets.AWS_ROLE_ARN }}}}
          aws-region: ${{{{ env.AWS_REGION }}}}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{{{ steps.ecr.outputs.registry }}}}/${{{{ env.ECR_REPOSITORY }}}}:${{{{ env.IMAGE_TAG }}}} .
          docker push ${{{{ steps.ecr.outputs.registry }}}}/${{{{ env.ECR_REPOSITORY }}}}:${{{{ env.IMAGE_TAG }}}}

  # ── Stage 3: Deploy to EKS ──
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{{{ secrets.AWS_ROLE_ARN }}}}
          aws-region: ${{{{ env.AWS_REGION }}}}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{{{ env.EKS_CLUSTER }}}} --region ${{{{ env.AWS_REGION }}}}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app app=${{{{ steps.ecr.outputs.registry }}}}/${{{{ env.ECR_REPOSITORY }}}}:${{{{ env.IMAGE_TAG }}}} -n app-production
          kubectl rollout status deployment/app -n app-production --timeout=300s"""


def gen_aws_terraform(stack: list, files: list) -> str:
    """Generate Terraform IaC for AWS: VPC, EC2/ECS, S3, RDS/DocumentDB, ECR."""
    lang = _detect_primary_lang(stack)
    has_pg = any(k in stack for k in ["PostgreSQL", "Django", "SQLAlchemy"])
    has_mongo = "MongoDB" in stack or any("mongo" in f.lower() for f in files)

    db_block = ""
    if has_pg:
        db_block = """
# --- RDS PostgreSQL ---
resource "aws_db_instance" "postgres" {
  identifier           = "${var.app_name}-db"
  engine               = "postgres"
  engine_version       = "16.3"
  instance_class       = "db.t3.micro"
  allocated_storage    = 20
  db_name              = var.app_name
  username             = var.db_user
  password             = var.db_password
  skip_final_snapshot  = true
  vpc_security_group_ids = [aws_security_group.db.id]
  db_subnet_group_name = aws_db_subnet_group.main.name
  tags = { Name = "${var.app_name}-rds" }
}"""
    elif has_mongo:
        db_block = """
# --- DocumentDB (MongoDB-compatible) ---
resource "aws_docdb_cluster" "mongo" {
  cluster_identifier  = "${var.app_name}-docdb"
  engine              = "docdb"
  master_username     = var.db_user
  master_password     = var.db_password
  skip_final_snapshot = true
  vpc_security_group_ids = [aws_security_group.db.id]
}"""

    return f"""# === Terraform AWS Infrastructure ===
# Generated by ShipSage
# Provisions: VPC, ECR, EKS, S3, {"RDS PostgreSQL" if has_pg else "DocumentDB" if has_mongo else "No DB"}

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{ source = "hashicorp/aws", version = "~> 5.0" }}
  }}
  backend "s3" {{
    bucket = "shipsage-tfstate"
    key    = "infra/terraform.tfstate"
    region = "us-east-1"
  }}
}}

provider "aws" {{
  region = var.aws_region
}}

variable "app_name"    {{ default = "app" }}
variable "aws_region"  {{ default = "us-east-1" }}
variable "db_user"     {{ default = "admin" }}
variable "db_password" {{ sensitive = true }}

# --- VPC ---
module "vpc" {{
  source  = "terraform-aws-modules/vpc/aws"
  version = "5.5.0"
  name    = "${{var.app_name}}-vpc"
  cidr    = "10.0.0.0/16"
  azs             = ["${{var.aws_region}}a", "${{var.aws_region}}b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]
  enable_nat_gateway = true
  single_nat_gateway = true
  tags = {{ Project = var.app_name }}
}}

# --- ECR Repository ---
resource "aws_ecr_repository" "app" {{
  name                 = var.app_name
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration {{ scan_on_push = true }}
}}

# --- EKS Cluster ---
module "eks" {{
  source          = "terraform-aws-modules/eks/aws"
  version         = "20.0"
  cluster_name    = "${{var.app_name}}-cluster"
  cluster_version = "1.29"
  vpc_id          = module.vpc.vpc_id
  subnet_ids      = module.vpc.private_subnets
  eks_managed_node_groups = {{
    default = {{
      instance_types = ["t3.medium"]
      min_size       = 2
      max_size       = 5
      desired_size   = 3
    }}
  }}
}}

# --- S3 Bucket (assets/backups) ---
resource "aws_s3_bucket" "assets" {{
  bucket = "${{var.app_name}}-assets-${{var.aws_region}}"
  tags   = {{ Name = "${{var.app_name}}-assets" }}
}}

resource "aws_s3_bucket_versioning" "assets" {{
  bucket = aws_s3_bucket.assets.id
  versioning_configuration {{ status = "Enabled" }}
}}

# --- Security Groups ---
resource "aws_security_group" "db" {{
  name_prefix = "${{var.app_name}}-db-"
  vpc_id      = module.vpc.vpc_id
  ingress {{
    from_port       = {5432 if has_pg else 27017}
    to_port         = {5432 if has_pg else 27017}
    protocol        = "tcp"
    security_groups = [module.eks.cluster_security_group_id]
  }}
}}

resource "aws_db_subnet_group" "main" {{
  name       = "${{var.app_name}}-db-subnet"
  subnet_ids = module.vpc.private_subnets
}}
{db_block}

# --- Outputs ---
output "ecr_url"      {{ value = aws_ecr_repository.app.repository_url }}
output "eks_endpoint"  {{ value = module.eks.cluster_endpoint }}
output "s3_bucket"     {{ value = aws_s3_bucket.assets.bucket }}"""


def gen_monitoring(stack: list) -> str:
    """Generate ELK Stack + Prometheus + Grafana monitoring configs."""
    return """# === Monitoring & Observability Stack ===
# Generated by ShipSage

# ──────────────────────────────────────
# docker-compose.monitoring.yml
# ──────────────────────────────────────
version: '3.9'

services:
  # --- ELK Stack ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    depends_on: [elasticsearch]
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    depends_on: [elasticsearch]
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  # --- Prometheus + Grafana ---
  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.4.0
    depends_on: [prometheus]
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  es_data:
  grafana_data:

# ──────────────────────────────────────
# prometheus.yml
# ──────────────────────────────────────
# global:
#   scrape_interval: 15s
# scrape_configs:
#   - job_name: 'app'
#     static_configs:
#       - targets: ['app:8000']
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']

# ──────────────────────────────────────
# logstash.conf
# ──────────────────────────────────────
# input {
#   beats { port => 5044 }
#   tcp { port => 5000, codec => json }
# }
# filter {
#   if [message] =~ "ERROR" { mutate { add_tag => ["error"] } }
# }
# output {
#   elasticsearch {
#     hosts => ["http://elasticsearch:9200"]
#     index => "app-logs-%{+YYYY.MM.dd}"
#   }
# }"""


def gen_env_and_nginx(stack: list, files: list) -> str:
    """Generate .env template + Nginx reverse proxy + Airflow DAG."""
    lang = _detect_primary_lang(stack)
    port = {"python": 8000, "node": 3000, "go": 8080, "java": 8080}.get(lang, 8000)
    has_pg = any(k in stack for k in ["PostgreSQL", "Django", "SQLAlchemy"])
    has_mongo = "MongoDB" in stack
    has_redis = "Redis" in stack
    is_data = any(k in stack for k in ["pandas", "Airflow", "Spark"]) or any("data" in f.lower() or "pipeline" in f.lower() or "etl" in f.lower() for f in files)

    env = f"""# === .env.template ===
# Generated by ShipSage — fill in your values

# App
APP_ENV=production
APP_PORT={port}
APP_SECRET_KEY=CHANGE_ME_TO_RANDOM_STRING
LOG_LEVEL=info

# AWS
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET=app-assets"""

    if has_pg:
        env += """

# PostgreSQL
DB_HOST=postgres
DB_PORT=5432
DB_USER=app
DB_PASS=CHANGE_ME
DB_NAME=appdb
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"""

    if has_mongo:
        env += """

# MongoDB
MONGO_HOST=mongo
MONGO_PORT=27017
MONGO_USER=root
MONGO_PASS=CHANGE_ME
MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}"""

    if has_redis:
        env += """

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0"""

    nginx = f"""

# ══════════════════════════════════════
# === nginx.conf (Reverse Proxy) ===
# ══════════════════════════════════════

upstream app_backend {{
    server app:{port};
}}

server {{
    listen 80;
    server_name app.example.com;
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name app.example.com;

    ssl_certificate     /etc/ssl/certs/app.crt;
    ssl_certificate_key /etc/ssl/private/app.key;

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {{
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    location /static/ {{
        alias /var/www/static/;
        expires 30d;
    }}
}}"""

    airflow = ""
    if is_data:
        airflow = """

# ══════════════════════════════════════
# === Airflow DAG (Data Pipeline) ===
# ══════════════════════════════════════

# from airflow import DAG
# from airflow.operators.python import PythonOperator
# from datetime import datetime, timedelta
#
# default_args = {
#     'owner': 'data-team',
#     'retries': 2,
#     'retry_delay': timedelta(minutes=5),
# }
#
# with DAG(
#     'app_data_pipeline',
#     default_args=default_args,
#     schedule_interval='@daily',
#     start_date=datetime(2026, 1, 1),
#     catchup=False,
# ) as dag:
#     extract = PythonOperator(task_id='extract', python_callable=extract_data)
#     transform = PythonOperator(task_id='transform', python_callable=transform_data)
#     load = PythonOperator(task_id='load', python_callable=load_data)
#     extract >> transform >> load"""

    return env + nginx + airflow


# ── Internal helpers ──

def _detect_primary_lang(stack: list) -> str:
    for s in stack:
        if s in ["Python", "FastAPI", "Flask", "Django"]: return "python"
        if s in ["JavaScript", "Express.js", "React", "Next.js"]: return "node"
        if s in ["Go"]: return "go"
        if s in ["Java", "Spring Boot"]: return "java"
        if s in ["Rust"]: return "rust"
    return "python"


def _dockerfile_python(files):
    has_req = any("requirements.txt" in f for f in files)
    return f"""FROM python:3.12-slim AS builder
WORKDIR /app
{'COPY requirements.txt .' if has_req else '# No requirements.txt found'}
{'RUN pip install --no-cache-dir --prefix=/install -r requirements.txt' if has_req else ''}

FROM python:3.12-slim
WORKDIR /app
{'COPY --from=builder /install /usr/local' if has_req else ''}
COPY . .
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8000/health || exit 1
CMD ["python", "main.py"]"""


def _dockerfile_node(files):
    return """FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1
CMD ["node", "index.js"]"""


def _dockerfile_go(files):
    return """FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /server .

FROM alpine:3.19
COPY --from=builder /server /server
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:8080/health || exit 1
CMD ["/server"]"""


def _dockerfile_java():
    return """FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY . .
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-alpine
COPY --from=builder /app/target/*.jar /app.jar
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8080/actuator/health || exit 1
CMD ["java", "-jar", "/app.jar"]"""


def _dockerfile_rust():
    return """FROM rust:1.77-slim AS builder
WORKDIR /app
COPY Cargo.* ./
RUN mkdir src && echo "fn main(){}" > src/main.rs && cargo build --release && rm -rf src
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/app /usr/local/bin/
EXPOSE 8080
CMD ["app"]"""
